// English irregular verbs with Ukrainian translations
// lvl: easy (top-100 most common) | medium | hard
window.VERBS = [
  // EASY — most common everyday verbs
  { v1: "be", v2: "was/were", v3: "been", ua: "бути", lvl: "easy" },
  { v1: "have", v2: "had", v3: "had", ua: "мати", lvl: "easy" },
  { v1: "do", v2: "did", v3: "done", ua: "робити", lvl: "easy" },
  { v1: "say", v2: "said", v3: "said", ua: "казати", lvl: "easy" },
  { v1: "go", v2: "went", v3: "gone", ua: "йти", lvl: "easy" },
  { v1: "get", v2: "got", v3: "got/gotten", ua: "отримати", lvl: "easy" },
  { v1: "make", v2: "made", v3: "made", ua: "робити, виготовляти", lvl: "easy" },
  { v1: "know", v2: "knew", v3: "known", ua: "знати", lvl: "easy" },
  { v1: "think", v2: "thought", v3: "thought", ua: "думати", lvl: "easy" },
  { v1: "take", v2: "took", v3: "taken", ua: "брати", lvl: "easy" },
  { v1: "see", v2: "saw", v3: "seen", ua: "бачити", lvl: "easy" },
  { v1: "come", v2: "came", v3: "come", ua: "приходити", lvl: "easy" },
  { v1: "give", v2: "gave", v3: "given", ua: "давати", lvl: "easy" },
  { v1: "find", v2: "found", v3: "found", ua: "знаходити", lvl: "easy" },
  { v1: "tell", v2: "told", v3: "told", ua: "розповідати", lvl: "easy" },
  { v1: "become", v2: "became", v3: "become", ua: "ставати", lvl: "easy" },
  { v1: "leave", v2: "left", v3: "left", ua: "залишати, йти", lvl: "easy" },
  { v1: "feel", v2: "felt", v3: "felt", ua: "відчувати", lvl: "easy" },
  { v1: "put", v2: "put", v3: "put", ua: "класти", lvl: "easy" },
  { v1: "bring", v2: "brought", v3: "brought", ua: "приносити", lvl: "easy" },
  { v1: "begin", v2: "began", v3: "begun", ua: "починати", lvl: "easy" },
  { v1: "keep", v2: "kept", v3: "kept", ua: "тримати", lvl: "easy" },
  { v1: "hold", v2: "held", v3: "held", ua: "тримати, утримувати", lvl: "easy" },
  { v1: "write", v2: "wrote", v3: "written", ua: "писати", lvl: "easy" },
  { v1: "stand", v2: "stood", v3: "stood", ua: "стояти", lvl: "easy" },
  { v1: "hear", v2: "heard", v3: "heard", ua: "чути", lvl: "easy" },
  { v1: "let", v2: "let", v3: "let", ua: "дозволяти", lvl: "easy" },
  { v1: "mean", v2: "meant", v3: "meant", ua: "означати", lvl: "easy" },
  { v1: "set", v2: "set", v3: "set", ua: "ставити, встановлювати", lvl: "easy" },
  { v1: "meet", v2: "met", v3: "met", ua: "зустрічати", lvl: "easy" },
  { v1: "run", v2: "ran", v3: "run", ua: "бігти", lvl: "easy" },
  { v1: "pay", v2: "paid", v3: "paid", ua: "платити", lvl: "easy" },
  { v1: "sit", v2: "sat", v3: "sat", ua: "сидіти", lvl: "easy" },
  { v1: "speak", v2: "spoke", v3: "spoken", ua: "говорити", lvl: "easy" },
  { v1: "read", v2: "read", v3: "read", ua: "читати", lvl: "easy" },
  { v1: "lose", v2: "lost", v3: "lost", ua: "втрачати, програвати", lvl: "easy" },
  { v1: "send", v2: "sent", v3: "sent", ua: "надсилати", lvl: "easy" },
  { v1: "build", v2: "built", v3: "built", ua: "будувати", lvl: "easy" },
  { v1: "understand", v2: "understood", v3: "understood", ua: "розуміти", lvl: "easy" },
  { v1: "break", v2: "broke", v3: "broken", ua: "ламати", lvl: "easy" },
  { v1: "spend", v2: "spent", v3: "spent", ua: "витрачати", lvl: "easy" },
  { v1: "cut", v2: "cut", v3: "cut", ua: "різати", lvl: "easy" },
  { v1: "buy", v2: "bought", v3: "bought", ua: "купувати", lvl: "easy" },
  { v1: "drive", v2: "drove", v3: "driven", ua: "вести (авто)", lvl: "easy" },
  { v1: "choose", v2: "chose", v3: "chosen", ua: "обирати", lvl: "easy" },

  // MEDIUM
  { v1: "win", v2: "won", v3: "won", ua: "вигравати", lvl: "medium" },
  { v1: "eat", v2: "ate", v3: "eaten", ua: "їсти", lvl: "medium" },
  { v1: "drink", v2: "drank", v3: "drunk", ua: "пити", lvl: "medium" },
  { v1: "sleep", v2: "slept", v3: "slept", ua: "спати", lvl: "medium" },
  { v1: "fly", v2: "flew", v3: "flown", ua: "літати", lvl: "medium" },
  { v1: "ride", v2: "rode", v3: "ridden", ua: "їздити верхи", lvl: "medium" },
  { v1: "throw", v2: "threw", v3: "thrown", ua: "кидати", lvl: "medium" },
  { v1: "swim", v2: "swam", v3: "swum", ua: "плавати", lvl: "medium" },
  { v1: "catch", v2: "caught", v3: "caught", ua: "ловити", lvl: "medium" },
  { v1: "sing", v2: "sang", v3: "sung", ua: "співати", lvl: "medium" },
  { v1: "wear", v2: "wore", v3: "worn", ua: "носити (одяг)", lvl: "medium" },
  { v1: "fall", v2: "fell", v3: "fallen", ua: "падати", lvl: "medium" },
  { v1: "draw", v2: "drew", v3: "drawn", ua: "малювати", lvl: "medium" },
  { v1: "grow", v2: "grew", v3: "grown", ua: "рости", lvl: "medium" },
  { v1: "rise", v2: "rose", v3: "risen", ua: "підніматися", lvl: "medium" },
  { v1: "lie", v2: "lay", v3: "lain", ua: "лежати", lvl: "medium" },
  { v1: "lay", v2: "laid", v3: "laid", ua: "класти, покласти", lvl: "medium" },
  { v1: "hide", v2: "hid", v3: "hidden", ua: "ховати", lvl: "medium" },
  { v1: "hit", v2: "hit", v3: "hit", ua: "вдаряти", lvl: "medium" },
  { v1: "hurt", v2: "hurt", v3: "hurt", ua: "ранити, боліти", lvl: "medium" },
  { v1: "fight", v2: "fought", v3: "fought", ua: "боротися", lvl: "medium" },
  { v1: "forget", v2: "forgot", v3: "forgotten", ua: "забувати", lvl: "medium" },
  { v1: "freeze", v2: "froze", v3: "frozen", ua: "заморожувати", lvl: "medium" },
  { v1: "bite", v2: "bit", v3: "bitten", ua: "кусати", lvl: "medium" },
  { v1: "blow", v2: "blew", v3: "blown", ua: "дути", lvl: "medium" },
  { v1: "dig", v2: "dug", v3: "dug", ua: "копати", lvl: "medium" },
  { v1: "lead", v2: "led", v3: "led", ua: "вести, керувати", lvl: "medium" },
  { v1: "lend", v2: "lent", v3: "lent", ua: "позичати (комусь)", lvl: "medium" },
  { v1: "shake", v2: "shook", v3: "shaken", ua: "трясти", lvl: "medium" },
  { v1: "shine", v2: "shone", v3: "shone", ua: "сяяти", lvl: "medium" },
  { v1: "shoot", v2: "shot", v3: "shot", ua: "стріляти", lvl: "medium" },
  { v1: "sink", v2: "sank", v3: "sunk", ua: "тонути", lvl: "medium" },
  { v1: "smell", v2: "smelt", v3: "smelt", ua: "пахнути", lvl: "medium" },
  { v1: "spread", v2: "spread", v3: "spread", ua: "поширювати", lvl: "medium" },
  { v1: "steal", v2: "stole", v3: "stolen", ua: "красти", lvl: "medium" },
  { v1: "stick", v2: "stuck", v3: "stuck", ua: "застрягати, клеїти", lvl: "medium" },
  { v1: "teach", v2: "taught", v3: "taught", ua: "вчити (когось)", lvl: "medium" },
  { v1: "tear", v2: "tore", v3: "torn", ua: "рвати", lvl: "medium" },
  { v1: "burn", v2: "burnt", v3: "burnt", ua: "горіти", lvl: "medium" },
  { v1: "cost", v2: "cost", v3: "cost", ua: "коштувати", lvl: "medium" },
  { v1: "deal", v2: "dealt", v3: "dealt", ua: "мати справу", lvl: "medium" },
  { v1: "feed", v2: "fed", v3: "fed", ua: "годувати", lvl: "medium" },
  { v1: "fit", v2: "fit", v3: "fit", ua: "підходити (за розміром)", lvl: "medium" },
  { v1: "hang", v2: "hung", v3: "hung", ua: "висіти, вішати", lvl: "medium" },
  { v1: "light", v2: "lit", v3: "lit", ua: "запалювати", lvl: "medium" },
  { v1: "ring", v2: "rang", v3: "rung", ua: "дзвонити", lvl: "medium" },
  { v1: "shut", v2: "shut", v3: "shut", ua: "зачиняти", lvl: "medium" },
  { v1: "sweep", v2: "swept", v3: "swept", ua: "підмітати", lvl: "medium" },
  { v1: "swing", v2: "swung", v3: "swung", ua: "гойдати, розмахувати", lvl: "medium" },

  // HARD — rarer / tricky patterns
  { v1: "arise", v2: "arose", v3: "arisen", ua: "виникати", lvl: "hard" },
  { v1: "awake", v2: "awoke", v3: "awoken", ua: "прокидатися", lvl: "hard" },
  { v1: "bear", v2: "bore", v3: "borne", ua: "нести, терпіти", lvl: "hard" },
  { v1: "beat", v2: "beat", v3: "beaten", ua: "бити, перемагати", lvl: "hard" },
  { v1: "bend", v2: "bent", v3: "bent", ua: "гнути", lvl: "hard" },
  { v1: "bet", v2: "bet", v3: "bet", ua: "битися об заклад", lvl: "hard" },
  { v1: "bind", v2: "bound", v3: "bound", ua: "звʼязувати", lvl: "hard" },
  { v1: "breed", v2: "bred", v3: "bred", ua: "розводити", lvl: "hard" },
  { v1: "broadcast", v2: "broadcast", v3: "broadcast", ua: "транслювати", lvl: "hard" },
  { v1: "burst", v2: "burst", v3: "burst", ua: "вибухати, лопатися", lvl: "hard" },
  { v1: "cast", v2: "cast", v3: "cast", ua: "кидати, відливати", lvl: "hard" },
  { v1: "cling", v2: "clung", v3: "clung", ua: "чіплятися", lvl: "hard" },
  { v1: "creep", v2: "crept", v3: "crept", ua: "повзти", lvl: "hard" },
  { v1: "dwell", v2: "dwelt", v3: "dwelt", ua: "мешкати", lvl: "hard" },
  { v1: "flee", v2: "fled", v3: "fled", ua: "тікати", lvl: "hard" },
  { v1: "fling", v2: "flung", v3: "flung", ua: "жбурляти", lvl: "hard" },
  { v1: "forbid", v2: "forbade", v3: "forbidden", ua: "забороняти", lvl: "hard" },
  { v1: "forgive", v2: "forgave", v3: "forgiven", ua: "прощати", lvl: "hard" },
  { v1: "forsake", v2: "forsook", v3: "forsaken", ua: "покидати", lvl: "hard" },
  { v1: "grind", v2: "ground", v3: "ground", ua: "молоти", lvl: "hard" },
  { v1: "kneel", v2: "knelt", v3: "knelt", ua: "ставати на коліна", lvl: "hard" },
  { v1: "lean", v2: "leant", v3: "leant", ua: "схилятися", lvl: "hard" },
  { v1: "leap", v2: "leapt", v3: "leapt", ua: "стрибати", lvl: "hard" },
  { v1: "mistake", v2: "mistook", v3: "mistaken", ua: "помилятися", lvl: "hard" },
  { v1: "overcome", v2: "overcame", v3: "overcome", ua: "долати", lvl: "hard" },
  { v1: "rid", v2: "rid", v3: "rid", ua: "позбавляти", lvl: "hard" },
  { v1: "seek", v2: "sought", v3: "sought", ua: "шукати", lvl: "hard" },
  { v1: "shed", v2: "shed", v3: "shed", ua: "скидати, проливати", lvl: "hard" },
  { v1: "slay", v2: "slew", v3: "slain", ua: "вбивати", lvl: "hard" },
  { v1: "slide", v2: "slid", v3: "slid", ua: "ковзати", lvl: "hard" },
  { v1: "sling", v2: "slung", v3: "slung", ua: "перекидати, метати", lvl: "hard" },
  { v1: "sow", v2: "sowed", v3: "sown", ua: "сіяти", lvl: "hard" },
  { v1: "stride", v2: "strode", v3: "stridden", ua: "крокувати", lvl: "hard" },
  { v1: "strike", v2: "struck", v3: "struck", ua: "вдаряти, бастувати", lvl: "hard" },
  { v1: "strive", v2: "strove", v3: "striven", ua: "прагнути", lvl: "hard" },
  { v1: "swear", v2: "swore", v3: "sworn", ua: "клястися", lvl: "hard" },
  { v1: "weave", v2: "wove", v3: "woven", ua: "ткати", lvl: "hard" },
  { v1: "weep", v2: "wept", v3: "wept", ua: "плакати", lvl: "hard" },
  { v1: "wind", v2: "wound", v3: "wound", ua: "обвивати, заводити", lvl: "hard" },
  { v1: "withdraw", v2: "withdrew", v3: "withdrawn", ua: "відкликати, знімати", lvl: "hard" },
];
